{% set name = "cmpitool" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmpitool-{{ version }}.tar.gz
  sha256: ec7c0f1e2aebd0f3db108bcbbc016c3654f922c4814e0233b11436fd5b17e4e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - matplotlib-base
    - numpy
    - pandas >=1.0.0
    - pooch
    - regionmask
    - seaborn
    - tqdm
    - xarray

test:
  imports:
    - cmpitool
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JanStreffing/cmpitool
  summary: 'Climate Model Performance Indicies (CMPI) toolbox'
  description: |
    cmpitool implements the calculation of Climate Model Performance Indicies after https://doi.org/10.1175/BAMS-89-3-303
  license: GPL-3.0-or-later
  license_file: LICENCE
  doc_url: https://cmpitool.readthedocs.io/
  dev_url: https://github.com/JanStreffing/cmpitool

extra:
  recipe-maintainers:
    - JanStreffing
